// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import FormSubmissionController from "./form_submission_controller"
import ModalController from "./modal_controller"
import MessageInputController from "./message_input_controller"
import ChatListController from "./chat_list_controller"
import SchemaModalController from "./schema_modal_controller"
import MarkdownController from "./markdown_controller"
import ChatController from "./chat_controller"

application.register("form-submission", FormSubmissionController)
application.register("modal", ModalController)
application.register("message-input", MessageInputController)
application.register("chat-list", ChatListController)
application.register("schema-modal", SchemaModalController)
application.register("markdown", MarkdownController)
application.register("chat", ChatController)
