// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import FormSubmissionController from "./form_submission_controller"
import ModalController from "./modal_controller"

application.register("form-submission", FormSubmissionController)
application.register("modal", ModalController)
